### ISSUE TITLE
Ectyper outputs different results depending on input format

### ISSUE THREAD

**Issue by arshdeep1k** [phac-nml/ecoli_serotyping#93] opened 2024-07-30 00:57 UTC
Hello, 

I have encountered an issue with the pipeline. It gives different results based on how the input is provided, one fasta file vs directory of fasta files vs comma-separated fasta files. 

- When I provide a directory of fasta files as an input, or more than one comma-separated fasta files, there is one sequence with no O-antigen detected. 
- When I provide only one single input fasta from that sample as an input, It produces the O-antigen result. 

Here are the files when run using one input.
[2419114246B1_blast_output_alleles.txt](https://github.com/user-attachments/files/16420476/2419114246B1_blast_output_alleles.txt)
[2419114246B1_ectyper.log](https://github.com/user-attachments/files/16420477/2419114246B1_ectyper.log)

Here are the files when run using multiple inputs
[2inputs_blast_output_alleles.txt](https://github.com/user-attachments/files/16420498/2inputs_blast_output_alleles.txt)
[2inputs_ectyper.log](https://github.com/user-attachments/files/16420499/2inputs_ectyper.log)

We use the pipeline to report serotyping for E.coli in our Public Health lab, It"ll be great if you can look into this issue.
Thank you

**Comment by kbessonov1984** [comment] 2024-10-03 20:12
Hello,
This issue should be fixed in the version 2.0.0 of the tool and had to do with reporting BLAST results for O/H antigens only for the last hit, now this is corrected and should work as intended on multiple inputs. You can install latest pre-release build from https://github.com/phac-nml/ecoli_serotyping/tree/v2.0.0. Test it and let me know

**Closed** 2024-10-12 03:37 UTC
